### ISSUE TITLE
Rosette counterexample generation?

### ISSUE THREAD

**Issue by xuruiyang** [uwdb/Cosette#4]
I notice that all test cases in rosette are only checking equivalence of two queries. But the purpose of using rosette is to find counterexamples that can proof the inequality of two queries, am I right?

Could you specify that how to use the given Rosette codes to generate counterexample?

**Comment by Mestway** [comment]
In short, command like `(verify (same q1 q2)` is  for both verification and counter example generation.

The running result of the command above can be either `(unsat) ` if `q1` an `q2` are equal; otherwise, a concrete counter-example will be generated.  

Most examples in these test cases are not equal, for example, tests/aggr-join.rkt and a counter-example will be generated if you run it.

**Comment by xuruiyang** [comment]
Thank you for your quick responding!

So I think the name 'same' was confusing me. Maybe you want to rename it to 'not-same' :D
